### ISSUE TITLE
Delete button problem on tablet screen

### ISSUE THREAD

**Issue by berkanaslan** [bladeofgod/flutter_image_editor#1]
Hello,

On tablet screens, the delete button does not look like cellphone sizes.

<img width="256" alt="Vertical" src="https://i.imgur.com/fdEFp6C.png">
<img width="512" alt="Horizontal" src="https://i.imgur.com/6Kuug5B.png">

**Comment by bladeofgod** [comment]
sorry guy,this plugin is not adapted to the tablet. :)
