### ISSUE TITLE
修改为image_editor_dove-Swift.h后，运行还是报'image_editor_dove-Swift.h' file not found

### ISSUE THREAD

**Issue by Leo78ing** [bladeofgod/flutter_image_editor#12]
将ImageEditorPlugin.m文件里的image_editor-Swift.h修改成image_editor_dove-Swift.h了，还是提示'image_editor_dove-Swift.h' file not found

**Comment by junbaor** [comment]
@Leo78ing 请问关闭 issues 是已解决了吗？
