### ISSUE TITLE
iOS pod install fail

### ISSUE THREAD

**Issue by lijing89** [bladeofgod/flutter_image_editor#2]
risei@lideMBP ios % pod install
Analyzing dependencies
[!] No podspec found for `image_editor_dove` in `.symlinks/plugins/image_editor_dove/ios`

**Comment by lijing89** [comment]
rename ios/.symlinks/image_editor_dove/ios/image_editor.podspec   to image_editor_dove.podspec

**Comment by bladeofgod** [comment]
maybe is pod's name : image_editor. plz change it to image_editor_dove and retry.

**Comment by MehmetKaranlik** [comment]
Have you ever tried on ios ? Its not even on targets.

**Comment by bladeofgod** [comment]
> Have you ever tried on ios ? Its not even on targets.

no

**Comment by lijing89** [comment]
i have fixed this problem from [this blog ](https://blog.csdn.net/BFELFISH/article/details/119061812)

**Comment by bladeofgod** [comment]
> i have fixed this problem by referring to [this blog ](https://blog.csdn.net/BFELFISH/article/details/119061812)

make a pr?

**Comment by lijing89** [comment]
村里网不好，只能截图给你看我的改动了

**Comment by bladeofgod** [comment]
> 村里网不好，不能往github上提交代码，只能截图给你看我的改动了 <img alt="image" width="1095" src="https://user-images.githubusercontent.com/19546352/158535824-1bed4597-8480-4798-bdca-50bdfc61cc71.png">

欧克， 多谢

**Comment by MehmetKaranlik** [comment]
Finally got rid of problem -> Line 2 is image_editor_dove instead of image_editor/image_editor
