### ISSUE TITLE
IOS Error

### ISSUE THREAD

**Issue by MehmetKaranlik** [bladeofgod/flutter_image_editor#3]
`
Error output from Xcode build:
↳
    objc[88435]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x213ff3678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10833c2c8). One of the two will be used. Which one is undefined.
    objc[88435]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x213ff36c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10833c318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/q1/7mc8hw2532x8q_80f61ln3280000gn/T/flutter_tools.YWA6IZ/flutter_ios_build_temp_dirGHNr8H/temporary_xcresult_bundle
/opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.3/ios/Classes/strategies/PhonePermissionStrategy.m:50:35: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
        CTCarrier *carrier = [netInfo subscriberCellularProvider];
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      serviceSubscriberCellularProviders
In module 'CoreTelephony' imported from /opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.3/ios/Classes/strategies/PhonePermissionStrategy.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: property 'subscriberCellularProvider' is declared deprecated here
    @property(readonly, retain, nullable) CTCarrier *subscriberCellularProvider API_DEPRECATED_WITH_REPLACEMENT("serviceSubscriberCellularProviders", ios(4.0, 12.0)) API_UNAVAILABLE(macos);
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: 'subscriberCellularProvider' has been explicitly marked deprecated here
    1 warning generated.
    1 warning generated.
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Edit/EditImageViewController.swift:13:40: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol EditImageViewDelegate: class {
                                           ^~~~~
                                           AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Edit/EditImageViewController.swift:13:40: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol EditImageViewDelegate: class {
                                           ^~~~~
                                           AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Scan/CameraScannerViewController.swift:14:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol CameraScannerViewOutputDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Protocols/CaptureDevice.swift:12:25: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    protocol CaptureDevice: class {
                            ^~~~~
                            AnyObject
    /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/ios/Pods/WeScan/WeScan/Edit/EditImageViewController.swift:13:40: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    public protocol EditImageViewDelegate: class {
                                           ^~~~~
                                           AnyObject
    /opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/git/flutter_image_editor-84c052b6e1a76e3bea1dc52e6abdd179aa169f6e/ios/Classes/ImageEditorPlugin.m:8:9: fatal error: 'image_editor_dove-Swift.h' file not found
    #import "image_editor_dove-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/git/flutter_image_editor-84c052b6e1a76e3bea1dc52e6abdd179aa169f6e/ios/Classes/ImageEditorPlugin.m:8:9: fatal error: 'image_editor_dove-Swift.h' file not found
    #import "image_editor_dove-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Error: Couldn't resolve the package 'image_editor_pro' in 'package:image_editor_pro/image_editor_pro.dart'.
: Error: Not found: 'package:image_editor_pro/image_editor_pro.dart'
import 'package:image_editor_pro/image_editor_pro.dart';
           ^
    Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aimage_editor_pro%2Fimage_editor_pro.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:623:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:763:21)
    <asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:586:9)
    <asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)
    <asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
    <asynchronous suspension>
    Failed to package /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias.
    Command PhaseScriptExecution failed with a nonzero exit code
    ld: framework not found image_editor_dove
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    rsync: link_stat "/Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/build/ios/Debug-iphonesimulator/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/533514bb11/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
    rsync: link_stat "/Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/build/ios/Debug-iphonesimulator/App.framework" failed: No such file or directory (2)
    rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/533514bb11/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
    Unhandled exception:
    Exception: Command "rsync -av --delete --filter - .DS_Store /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/build/ios/Debug-iphonesimulator/App.framework /Users/mehmetkaranlik/Desktop/Repositories/Notititas/notitias/build/ios/Debug-iphonesimulator/Runner.app/Frameworks" exited with code 23
#0      Context.runSync
#1      Context.embedFlutterFrameworks
#2      Context.run
#3      main
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/q1/7mc8hw2532x8q_80f61ln3280000gn/T/flutter_tools.YWA6IZ/flutter_ios_build_temp_dirGHNr8H/temporary_xcresult_bundle
Lexical or Preprocessor Issue (Xcode): 'image_editor_dove-Swift.h' file not found
/opt/homebrew/Caskroom/flutter/2.8.0/flutter/.pub-cache/git/flutter_image_editor-84c052b6e1a76e3bea1dc52e6abdd179aa169f6e/ios/Classes/ImageEditorPlugin.m:7:8
Error (Xcode): Framework not found image_editor_dove
Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.
Exited (sigterm)
`
No matter what i do i cant pass this error.

**Comment by bladeofgod** [comment]
https://github.com/bladeofgod/flutter_image_editor/issues/2
