### ISSUE TITLE
IOS pods bug 

### ISSUE THREAD

**Issue by hesty** [bladeofgod/flutter_image_editor#4]
https://github.com/bladeofgod/flutter_image_editor/blob/84c052b6e1a76e3bea1dc52e6abdd179aa169f6e/ios/Classes/ImageEditorPlugin.m#L2

This line is not working.
Try this code to compile: #if __has_include(<image_editor_dove/image_editor_dove-Swift.h>)

**Comment by MehmetKaranlik** [comment]
Works like charm. Congrats

**Comment by hesty** [comment]
Solved together. @MehmetKaranlik  go ahead

**Comment by bladeofgod** [comment]
[plz pull this repository again.](https://github.com/bladeofgod/flutter_image_editor/issues/2)
