### ISSUE TITLE
Custom painter size and mosaic size

### ISSUE THREAD

**Issue by brandoneedyou** [bladeofgod/flutter_image_editor#5]
Hi, thank you for providing this amazing library.

I imported this lib in my project, but I realized that I cannot customize the painter size of "Draw" and Mosaic size, could you help me please?

**Comment by bladeofgod** [comment]
Hi, i just add a CanvasLauncher class for custom some initial value.
And, you can custom painter and mosaic size by use it.

ps: just updated to github, not on pub.
